title: Red Ant
email: ben@redant.com.au
description: >-
  Red Ant is a Technical Agency. We create & build exceptional digital products.
  These live as web sites, in mobile apps, and in social networks.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redant.com.au" # the base hostname & protocol for your site, e.g. http://example.com
url_host: "redant.com.au"
announcement_bar: true

# Build settings
permalink: /:title/
markdown: kramdown
google_analtyics: UA-421251-1

intercom: true
on_demand: false

gtm:
  dev: GTM-N3CM249
  prod: GTM-P7QNBDH

defaults:
  - scope:
      path: admin
    values:
      sitemap: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - docker-compose.yml
  - Dockerfile
  - esbuild.config.js
  - package.json
  - Rakefile
  - README.md
  - yarn.lock
  - yarn-error.log
