title: Red Ant
email: ben@redant.com.au
description: >-
  Red Ant is a Technical Agency. We create & build exceptional digital products.
  These live as web sites, in mobile apps, and in social networks.

social:
  name: Red Ant
  links:
    - https://twitter.com/r_e_d_a_n_t
    - https://www.linkedin.com/company/76862

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redant.com.au" # the base hostname & protocol for your site, e.g. http://example.com
announcement_bar: false

# Build settings
permalink: /:title/
markdown: kramdown

msclarity:
  dev: "gn8srwgeu9"
  prod: "gq7hxwmdua"

gtm:
  dev: GTM-N3CM249
  prod: GTM-P7QNBDH

defaults:
  - scope:
      path: admin
    values:
      sitemap: false

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - docker-compose.yml
  - Dockerfile
  - esbuild.config.js
  - package.json
  - Rakefile
  - README.md
  - yarn.lock
  - yarn-error.log

collections:
  assessment_sections:
    output: true
  assessment_submissions:
    output: true
  assessment_results:
    output: true
  assessment_book_call:
    output: true

postcss:
  cache: false
