version: "3"

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    working_dir: /srv/jekyll
    command: bash -c "bundle && yarn && jekyll serve --livereload --host 0.0.0.0"
    container_name: jekyll
    volumes:
      - .:/srv/jekyll
      - node_modules:/srv/jekyll/node_modules
    ports:
      - 4000:4000
      - 35729:35729

volumes:
  node_modules:
