version: "3"

services:
  esbuild: &default
    build: .
    command: yarn esbuild --watch
    volumes:
      - .:/srv/jekyll
      - node_modules:/srv/jekyll/node_modules

  jekyll:
    <<: *default
    command: bundle exec jekyll serve --livereload --host 0.0.0.0
    ports:
      - 4000:4000
      - 35729:35729

volumes:
  node_modules:
