---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url:
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bash -c "bundle install && yarn install"
  preview_docker_image: jekyll/jekyll:4.2.2
  mount_path: "/srv/jekyll"
  instant_preview_command: bash -c "jekyll serve --drafts --unpublished
    --future --port 8080 --host 0.0.0.0 -d _site"
